# AI-generated content may be incorrect
openapi: "3.0.0"
info:
  version: "3.0.0"
  title: "Simple Flask API - V3"
paths:
  /:
    get:
      responses:
        '200':
          description: Returns a greeting message
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"
